name: Android CI

on:
  push:
    branches: [ "browser2" ]
  pull_request:
    branches: [ "browser2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    # Add the following steps to commit and push the APK
    - name: Commit and Push APK
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/build/outputs/apk/debug/app-debug.apk # Adjust the path as needed
        git commit -m "Add built APK"
        git push
      if: success() # Only execute this step if the build was successful
